server:
  port: 8088
spring:
  application:
    name: content-center
  datasource:
    url: jdbc:mysql://39.97.252.60:3306/content-center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: hyj200091
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.252.60:8848
#        namespace: 4bce9045-12d2-4de3-9a49-2b53839564b7
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon:
#  eager-load:
#    enabled: true
#    clients: user-center
