server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.252.60:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: path_router1
          uri: lb://user-center
          predicates:
            - Path=/user/**
        - id: path_router2
          uri: lb://content-center
          predicates:
            - Path=/shares/**
        - id: path_router3
          uri: lb://content-center
          predicates:
            - Path=/notice/**
        - id: path_router4
          uri: lb://content-center
          predicates:
            - Path=/admin/shares/**
#        - id: header_router
#          uri: lb://user-center
#          predicates:
#            - TimeBetween=上午11:30,下午5:00
#      - id: after
#        uri: lb://user-center/user/{id}
##        uri: lb://user-center
#        predicates:
#          - Path=/user/{id}
#          - After=2020-10-09T09:00:00.000000+08:00[Asia/Shanghai]
#          - Method=GET
#      - id: query_route
#        uri: lb://content-center/shares/{id}
#        predicates:
#          - Path=/shares/{id}
#          # 当且仅当请求IP是192.168.1.1/24网段，例如192.168.1.10，才会转发到用户微服务
#          - RemoteAddr=172.26.48.1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace